### PR TITLE
Fix issues introduced by PR #48

### PR DESCRIPTION
**Pull request by jxtxzzw**
@ZhangYuS

### CODE REVIEW

**Comment by ultmaster** [comment]
Please resolve conflicts.

**Comment by jxtxzzw** [comment]
> Please resolve conflicts.

Still in processing, ZhangYuS found another bug after this PR. Will fix that together.

**Comment by ZhangYuS** [comment]
@ultmaster 麻烦帮 review 一下

**Comment by ZhangYuS** [comment]
@ultmaster 麻烦帮我重新 review 一下吧，又重写了一下......

**Comment by ultmaster** [comment]
Seems out-of-date to me. Closing it for now.

**Pull request closed without merging**
